version: "3.7"
services:
  local.webapi.postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "transactions"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  local.webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      DB_CONNECTION_STRING: "Host=local.webapi.postgresql;Port=5432;Database=transactions;User Id=root;Password=root;"
      TRANSACTION_TABLE_NAME: "transactions"
      TRANSACTION_SEQUENCE_TABLE_NAME: "transactions_sequences
    depends_on:
      - local.webapi.postgresql
