version: "3.7"
services:
  local.webapi.postgresql:
    image: postgres:11.22-bullseye
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]

  local.webapi.pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - POOL_MODE=session
    ports:
      - '6438:5432'
    depends_on:
      - local.webapi.postgresql

  local.webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      DB_CONNECTION_STRING: "Host=local.webapi.pgbouncer;Port=6438;Database=development;User Id=postgres;Password=postgres;"
      TRANSACTION_TABLE_NAME: "transactions"
      TRANSACTION_SEQUENCE_TABLE_NAME: "transactions_sequences"
    depends_on:
      - local.webapi.pgbouncer
