<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PackageId>InfraPostgreSQL</PackageId>
        <Nullable>disable</Nullable>
        <ImplicitUsings>false</ImplicitUsings>
        <EnableProfileGuidedOptimization>true</EnableProfileGuidedOptimization>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Dapper.SqlBuilder" Version="2.1.66" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="Npgsql.DependencyInjection" Version="10.0.3" />
    </ItemGroup>

</Project>
