name: Mutation Tests

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/mutation-testing.yml"
  schedule:
    - cron: "30 3 * * 1-5"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: 1 # Disable the .NET welcome message
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 # Opt out of the .NET SDK telemetry feature

jobs:
  run-mutation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup .NET [v10.0.x]
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Show Docker Compose version
        run: docker compose version

      - name: Start PostgreSQL Container
        run: docker compose -f src/test/IntegrationTest.Infra.PostgreSql/docker-compose.yml up -d

      - name: Resolve dependencies
        run: dotnet restore --force --no-cache

      - name: Hack [issue "MSB3026 Unable to copy file" for EmbeddedResources]
        run: |
          mkdir -p src/test/IntegrationTest.EntryPoint.WebApi/bin/Debug/net10.0/{pt-br,en-us}
          mkdir -p src/test/IntegrationTest.EntryPoint.WebApi/bin/Release/net10.0/{pt-br,en-us}

      - name: Build in Debug Mode
        run: dotnet build --configuration Debug --no-restore

      - name: Mutation [Core]
        working-directory: ./src/test/UnitTest.Core
        run: |
          dotnet tool restore
          dotnet stryker

      - name: Copy report to right place [Core]
        run: |
          mkdir -p ./docs/mutation-reports/Core
          find ./src/test/UnitTest.Core/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/Core' ';'

      - name: Mutation [EntryPoint WebApi]
        working-directory: ./src/test/IntegrationTest.EntryPoint.WebApi
        run: |
          dotnet tool restore
          dotnet stryker

      - name: Copy report to right place [WebApi]
        run: |
          mkdir -p ./docs/mutation-reports/EntryPoint.WebApi
          find ./src/test/IntegrationTest.EntryPoint.WebApi/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/EntryPoint.WebApi' ';'

      - name: Mutation [Infra PostgreSQL]
        working-directory: ./src/test/IntegrationTest.Infra.PostgreSql
        run: |
          dotnet tool restore
          dotnet stryker

      - name: Copy report to right place [Infra PostgreSQL]
        run: |
          mkdir -p ./docs/mutation-reports/Core ./docs/mutation-reports/EntryPoint.WebApi ./docs/mutation-reports/Infra.PostgreSql
          find ./src/test/UnitTest.Core/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/Core' ';' || true
          find ./src/test/IntegrationTest.EntryPoint.WebApi/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/EntryPoint.WebApi' ';' || true
          find ./src/test/IntegrationTest.Infra.PostgreSql/StrykerOutput -name '*.html' -exec cp -prv '{}' './docs/mutation-reports/Infra.PostgreSql' ';' || true

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config pull.rebase false        
            git config --local user.email "action@github.com"
            git config --local user.name "Stryker.NET"
            git add docs/mutation-reports/
            git commit -m "doc(testing): update mutation reports"
            git pull origin main
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Environment Teardown
        if: always()
        run: |
          docker compose -f src/test/IntegrationTest.Infra.PostgreSql/docker-compose.yml down
          echo "Environment Teardown"
